repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: debug-statements
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: pretty-format-json
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: debug-statements
    -   id: fix-encoding-pragma
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v1.1.0
    hooks:
    -   id: reorder-python-imports
- repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
      - id: black
- repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

